apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matomo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - name: matomo
        image: matomo:latest
        ports:
        - name: http-port
          containerPort: 80
